# Generated by Django 5.0.1 on 2024-02-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0002_remove_contentitem_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='body',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
