# Generated by Django 5.0.1 on 2024-02-16 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cms_app', '0003_alter_contentitem_body_alter_contentitem_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Admin',
        ),
        migrations.RenameModel(
            old_name='ContentItem',
            new_name='Author',
        ),
    ]
