# Generated by Django 5.0.1 on 2024-02-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0005_category_author_summary_author_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('book', 'Book'), ('blog', 'Blog')], default=1, max_length=4),
            preserve_default=False,
        ),
    ]
