# Generated by Django 5.0.1 on 2024-02-16 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0006_remove_category_name_category_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cms_app.category'),
            preserve_default=False,
        ),
    ]
