# Generated by Django 5.0.1 on 2024-02-16 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0009_remove_category_category_type_category_name'),
    ]

    operations = [
    ]
