# Generated by Django 5.0.1 on 2024-02-16 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0010_auto_20240216_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
